### ISSUE TITLE
MR implementation not using the correct LD matrix

### ISSUE THREAD

**Issue by jrs95** [oxford-pharmacoepi/MR_Sclerostin#1]
Hi,

There are a couple of issues with your current implementation of the MR method:
- The LD matrix used is currently $r^2$. The generalized IVW method requires (signed) $r$ not $r^2$.
- The effect allele for each genetic variant has to be the same across the exposure data, the outcome data **and** the LD matrix. Currently you are missing the step that harmonizes the exposure-outcome data to the LD matrix.

Since the same LD matrix is used throughout your MR analyses, all of your MR results are affected.

For instance, using the [vignette](https://mrcieu.github.io/TwoSampleMR/articles/perform_mr.html#mr-estimates-when-instruments-are-correlated) from the TwoSampleMR package for dataset ebi-a-GCST005194 (CAD):

```
library(TwoSampleMR)

exposure_data <- read.csv("./Pruning/exposure_data.csv")

outcome_data <- extract_outcome_data(snps = exposure_data$SNP, outcomes = "ebi-a-GCST005194")

dat <- harmonise_data(exposure_data, outcome_data)
dat2 <- dat_to_MRInput(dat, get_correlation = TRUE)

MendelianRandomization::mr_ivw(dat2[[1]], correl = TRUE)
```

Yields:

```
Inverse-variance weighted method
(variants correlated, random-effect model)

Number of Variants : 6 

------------------------------------------------------------------
 Method Estimate Std Error  95% CI       p-value
    IVW   -0.087     0.080 -0.244, 0.069   0.274
------------------------------------------------------------------
Residual standard error =  0.981 
Residual standard error is set to 1 in calculation of confidence interval when its estimate is less than 1.
Heterogeneity test statistic (Cochran's Q) = 4.8120 on 5 degrees of freedom, (p-value = 0.4392). I^2 = 0.0%. 
```

So, the CAD result in Table 2 of the manuscript should read OR = 1.09 (0.93, 1.28) instead of OR = 1.25 (1.15, 1.35). 

Best wishes,

James Staley

_Dr James Staley
Computational Genetics Lead
UCB Pharma, 216 Bath Road, Slough, UK_

**Comment by martaalcalde** [comment]
Dear James,

Thank you sincerely for your feedback. We have implemented the suggested modifications and now we are in the process of updating the results accordingly.

All the best,

Marta
